### ISSUE TITLE
Unresponsive state when moving white clip from arranger to grid mode

### ISSUE THREAD

**Issue by benadamstyles** [SynthstromAudible/DelugeFirmware#2287] opened 2024-07-12 13:33 UTC
If you’re in grid mode, and then you use arranger, create a white clip, and then press and hold the white clip and press song to move it into the song view, you get stuck in grid mode and none of the buttons on the whole deluge work. You have to turn it off and on again.

It was in C1.0.1 and now is also in C1.1.0.

**Comment by pmatila** [comment] 2024-07-13 13:46
This seems like a duplicate of #1907, and in that case, there actually is a way out of the dead-end: hit an empty launch or the blue/green mode buttons.

**Comment by sapphire-arches** [comment] 2024-07-27 20:25
Yeah, this is a dupe. Thanks for the report!

**Closed by sapphire-arches** 2024-07-27 20:25 UTC
