### ISSUE TITLE
Getting "file not found" when pressing LOAD+SYNTH or turning SELECT knob

### ISSUE THREAD

**Issue by chewabledrapery** [SynthstromAudible/DelugeFirmware#1789] opened 2024-04-28 03:26 UTC
### Please describe the problem:

After flashing c1.1.0 Beethoven when I try to load a preset or scoll to next i get "file not foun error"

### What is the expected behavior?

To bring u a browse list or scroll to next/previous preset

### What hardware did you reproduce it with?

OLED

### What firmware did you reproduce it with?

other

### What is the firmware name:

deluge-v1_1_0-beta+2024_04_28-cc25fff.bin

**Comment by m-m-adams** [comment] 2024-04-28 03:58
I'm not able to reproduce this on my deluge 

Would you be able to install a debug build? There's a site here https://bfredl.github.io/delugeclient/app.html that will connect to the deluge over midi and get better error messages

**Comment by m-m-adams** [comment] 2024-04-28 04:09
Actually I bet your issues are related - it might be failing to load the preset properly, while browsing it doesn't try again until you press select so you're getting the file not found error

**Comment by chewabledrapery** [comment] 2024-04-28 05:22
> Actually I bet your issues are related - it might be failing to load the preset properly, while browsing it doesn't try again until you press select so you're getting the file not found error

Yeah that's what I was thinking tbh, i've put an example project in #1790

Thanks!

**Comment by chewabledrapery** [comment] 2024-04-28 05:24
> I'm not able to reproduce this on my deluge
> 
> Would you be able to install a debug build? There's a site here https://bfredl.github.io/delugeclient/app.html that will connect to the deluge over midi and get better error messages
> 
> Here's where you can get a debug build - https://github.com/SynthstromAudible/DelugeFirmware/actions/runs/8863312131

So I hook my deluge up to the USB of the PC then load this page? I'll give it a go... Thanks!

**Comment by chewabledrapery** [comment] 2024-04-28 05:40
> I'm not able to reproduce this on my deluge
> 
> Would you be able to install a debug build? There's a site here https://bfredl.github.io/delugeclient/app.html that will connect to the deluge over midi and get better error messages
> 
> Here's where you can get a debug build - https://github.com/SynthstromAudible/DelugeFirmware/actions/runs/8863312131

OK so got the deluge hooked up, displaying debug info and emulated display.

I still have the arpeg issue but not the "file not found" issue on this debug build...

**Comment by m-m-adams** [comment] 2024-04-28 05:55
Alright, thanks for checking. Not sure what the issue would be then

**Comment by m-m-adams** [comment] 2024-04-28 13:55
Is this happening with songs started on community? If it's just from official then possibly a duplicate of #1792

**Comment by ThePuny** [comment] 2024-04-28 18:04
> Is this happening with songs started on community? If it's just from official then possibly a duplicate of #1792

I am having the same issue as described also for songs started on Community.

**Comment by m-m-adams** [comment] 2024-04-28 19:01
Yeah there's a PR to fix it, the bug is caused by the song having preset file paths that no longer exist on the card. With the bugfix linked above (#1794) it'll just restart from the root synths folder when that happens

**Closed** 2024-04-28 20:13 UTC
Labels: bug

**Comment by chewabledrapery** [comment] 2024-04-29 04:48
> Is this happening with songs started on community? If it's just from official then possibly a duplicate of #1792

I definitely started this project on community, been on community since the first release.

**Comment by chewabledrapery** [comment] 2024-04-29 04:49
> Yeah there's a PR to fix it, the bug is caused by the song having preset file paths that no longer exist on the card. With the bugfix linked above (#1794) it'll just restart from the root synths folder when that happens

if that is the case I'll look through all my project xml and make sure all paths are valid...
