### ISSUE TITLE
CV/Gate clock output fails after long uptime

### ISSUE THREAD

**Issue by acook** [SynthstromAudible/DelugeFirmware#2132] opened 2024-06-15 04:07 UTC
### Please describe the problem:

If the Deluge is on for long periods of time the gate output clock will send a single pulse and then freeze.

### What is the expected behavior?

Regardless of uptime, the gate clock will continue functioning.

### What hardware did you reproduce it with?

OLED

### What firmware did you reproduce it with?

Release 1.0/Amadeus

### What is the firmware name:

1.1.0-BETA-E45865D

### If possible provide the steps to reproduce the issue and upload additional media:

1. Turn on
2. Configure CV/Gate output for clock mode
3. Observe functional clock output
4. _Wait_ (easy mode: leave it on overnight)
5. Press play
6. **Observe failure to send proper clock**
7. Restart Deluge
8. Observe functional clock output

---

This problem has also existed on the official firmware for as long as I can remember.

Probably the same underlying issue or at least related to: https://github.com/SynthstromAudible/DelugeFirmware/issues/2123

# UPDATE 2024-06-19

@m-m-adams discovered that this issue can be replicated without a wait time by turning the BPM up to very high settings, so no more leaving the Deluge on overnight to test it

**Comment by m-m-adams** [comment] 2024-06-18 20:55
Confirmed, sadly at one debug attempt per 24 hours or so this will probably take a while to fix...

**Comment by m-m-adams** [comment] 2024-06-18 21:12
I think this might be the same as 2144 - they both end up in a state where clockOutputPending isn't being set properly. 2144 is (poorly) fixed by having CV output handled exclusively by the ISR but this state isn't supposed to be possible anyway

<img width="344" alt="image" src="https://github.com/SynthstromAudible/DelugeFirmware/assets/52469396/e835b5f3-42d8-4f0f-8ac6-25c47b9ec7ea">

As shown here, they don't match so a clock should be pending - it's unclear how this happens

**Comment by m-m-adams** [comment] 2024-06-18 21:18
In fact all combinations seem to be possible 

<img width="265" alt="image" src="https://github.com/SynthstromAudible/DelugeFirmware/assets/52469396/c053992c-3c4e-49c6-8088-b8f645671bbd">

**Comment by m-m-adams** [comment] 2024-06-23 17:03
Duplicate of #2144, only difference is the clock starts to fall behind faster in nightly. Once the clock is behind it outputs 2 ticks at once to catch up which results in the gate not changing at all.

**Closed** 2024-06-23 17:04 UTC
Labels: bug

**Comment by m-m-adams** [comment] 2024-07-07 21:20
Confirmed this is now fixed
