### ISSUE TITLE
Crash - Audio as oscillator type

### ISSUE THREAD

**Issue by Evilpilli** [SynthstromAudible/DelugeFirmware#2816] opened 2024-10-16 17:21 UTC
### Please describe the problem:

Crashes when selecting audio as oscillator type, and changing the filter in automation view. 

### What is the expected behavior?

For it not to crash. 

### Is there a relevant Pull request?

No

### What hardware did you reproduce it with?

7SEG

### What firmware did you reproduce it with?

Nightly

**Comment by m-m-adams** [comment] 2024-11-06 18:11
I can't reproduce this - closing for now, happy to try again with more details

**Closed by m-m-adams** 2024-11-06 18:11 UTC

**Comment by Evilpilli** [comment] 2024-12-07 15:48
> I can't reproduce this - closing for now, happy to try again with more details

Tested this again on the recently nightly (Audio as input as oscillator is not a feature I use allot) and I can no longer reproduce the crash either. So seemingly fixed.
