### ISSUE TITLE
Crash when entering filters menu item on FM synth

### ISSUE THREAD

**Issue by sichtbeton** [SynthstromAudible/DelugeFirmware#1407] opened 2024-03-02 20:21 UTC
### Please describe the problem:

When you select the „filter „ menu item and press select, the deluge crashes. This happens in a blank new FM synth clip. There is no QR code, it just stops working and needs a reboot.

![image](https://github.com/SynthstromAudible/DelugeFirmware/assets/62035517/343c3631-3f13-4476-8b14-b4e113506fbd)

### What is the expected behavior?

No crash and actually enter the menu.

### Is there a relevant Pull request?

No

### What hardware did you reproduce it with?

OLED

### What firmware did you reproduce it with?

Nightly

### What is the firmware name:

1.2.0-NIGHTLY-24D683

### If possible provide the steps to reproduce the issue and upload additional media:

New synth clip
Change to FM mode
Enter sound menu via push “select”
Find “filter”
Push select

**Comment by joxihan** [comment] 2024-03-02 23:24
isn't it a duplicate of https://github.com/SynthstromAudible/DelugeFirmware/issues/1355 ?

**Comment by sapphire-arches** [comment] 2024-03-03 01:09
Yep, dupe of 1355.

**Closed by sapphire-arches** 2024-03-03 01:09 UTC
