### ISSUE TITLE
Same session names and preview load strangely 

### ISSUE THREAD

**Issue by Exmpl-xe** [SynthstromAudible/DelugeFirmware#2392] opened 2024-08-06 08:47 UTC
### Please describe the problem:

When using original firmware I created new sessions letting dely automatically name them (#.) , then created sessions with the same names (just #) , so I have 9. & 9  with c1.1 it will preview session 9 when 9. Is loaded. If I keep loading the next similar number it keeps looping back around.

### What is the expected behavior?

Load subsequently to the next session 

### Is there a relevant Pull request?

Maybe? #1069

### What hardware did you reproduce it with?

7SEG

### What firmware did you reproduce it with?

Release 1.1/Beethoven

### What is the firmware name:

C1.1.0

### If possible provide the steps to reproduce the issue and upload additional media:

As above, having the same automatically, and manually named session displays the others session prevew, & creates a loop of  load in to session, press load, scroll, repeat

**Comment by m-m-adams** [comment] 2024-08-07 16:23
I'm gonna close this as a duplicate

We're not sure of the cause (it's deep in some very legacy code) but the solution is to name a project using letters, then the auto incrementing works properly

**Closed by m-m-adams** 2024-08-07 16:23 UTC
