### ISSUE TITLE
All synth/kit clips Level and Pan values reset on song load

### ISSUE THREAD

**Issue by panicmechanic** [SynthstromAudible/DelugeFirmware#2790] opened 2024-10-07 17:18 UTC
### Please describe the problem:

In nightly, all synth or kit clips (but not audio clips) will reset their Level and Pan value to default (Level: 35 + Pan: 0) on loading the song. 

This has been a consistent bug for me since flashing nightly 18/09/24. It affects all my saves. Flashing the latest beta resolves it.

E.g. 

1. I have one stock drum kit clip in arranger mode, and I set it to Level: 14 and Pan: -3 
2. I save the song, the values remain
3. I load the save, the values are reset to 35 and 0

### What is the expected behavior?

Values should stay the same.

### What hardware did you reproduce it with?

OLED

### What firmware did you reproduce it with?

Nightly

### What is the firmware name:

1.2.0-NIGHTLY-02BE727

### If possible provide the steps to reproduce the issue and upload additional media:

Here's a track I just made. When I adjust the level/pan values of any clip (except audio clips) the values don't persist across saves.
[Bug Report.zip](https://github.com/user-attachments/files/17282314/Bug.Report.zip)

**Comment by m-m-adams** [comment] 2024-10-08 14:07
I believe this is a duplicate of #2710, just noticed differently

**Closed by m-m-adams** 2024-10-08 14:07 UTC
