### ISSUE TITLE
Stems export

### ISSUE THREAD

**Issue by nnicRomm** [SynthstromAudible/DelugeFirmware#2577] opened 2024-09-04 13:26 UTC
### Please describe the problem:

Stems export from arranger. It does export the tracks, but they only contain 5 seconds of music. However this files have the correct duration if loaded in the deluge as samples (i.e. in a drum kit). 
Tested with both freeverb and mutable, export to silence both on and off, on multiple songs, song fx off. Always same behaviour.

### What is the expected behavior?

Exported files should contain more music.

### What hardware did you reproduce it with?

OLED

### What firmware did you reproduce it with?

Beta

### What is the firmware name:

Chopin beta

### If possible provide the steps to reproduce the issue and upload additional media:

[SONG043 5.zip](https://github.com/user-attachments/files/16871221/SONG043.5.zip)

**Comment by m-m-adams** [comment] 2024-09-08 16:28
Duplicate of #2573

**Closed by m-m-adams** 2024-09-08 16:28 UTC

**Comment by seangoodvibes** [comment] 2024-09-11 22:28
@nnicRomm while not an ideal solution, we recommend the following to allow you to export stems:

## Troubleshooting

### I have a track that won't export

#### Scenario: Track(s) get exported with only 5 seconds of audio

Several users reported that their arranger stems were not getting exported properly as they included only 5 seconds of audio.

All of these users were using offline rendering.

All of these users had complex arrangements.

Solution:

For heavy arrangements, if you encounter the above issue, we recommend turning off `Offline Rendering` in the `SONG\EXPORT STEMS\CONFIGURE EXPORT\` menu.

The problem is due to memory filling up faster when using `Offline Rendering` compared to `Online (Live) Rendering`. We hope to find a solution for this problem as soon as possible.

**Comment by nnicRomm** [comment] 2024-09-12 09:23
@seangoodvibes Thanks man, I'll give it a try! :)
