### ISSUE TITLE
Audio only recording doesn't respect count in

### ISSUE THREAD

**Issue by m-m-adams** [SynthstromAudible/DelugeFirmware#479] opened 2023-08-30 00:47 UTC
### Please describe the problem:

Audio only recording doesn't respect count in

### What is the expected behavior?

Audio only recording should respect count in

### Is there a relevant Pull request?

No

### What hardware did you reproduce it with?

OLED

### What firmware did you reproduce it with?

Built from release/1.0

### If possible provide the steps to reproduce the issue and upload additional media:

enable count in
Make an audio clip and arm for recording
Delete  or disarm any instrument clips
press record then play

Observe: no count in

**Comment by ok-reza** [comment] 2023-11-03 19:12
this is expected behavior. the reason being that you can close an audio only recording whenever you want ('off the grid') and once the recording is closed it generates a new project tempo based on the audio file.

a couple workarounds when a count-in is desired is to enable the metronome (shift+tap tempo) before recording or have another clip that exists and is armed.

**Closed by ok-reza** 2023-11-03 19:12 UTC
Labels: bug
