### ISSUE TITLE
Pressing enter while saving a kit without typing a name doesn't save anything

### ISSUE THREAD

**Issue by bukru** [SynthstromAudible/DelugeFirmware#2658] opened 2024-09-15 18:14 UTC
### Please describe the problem:

In a kit, press [AUDITION] pad + [Midi] to convert the row in midi row and then choosing midi channel and note with gold knobs.
Save the kit.

When reloading the kit the configuration is lost.

### What is the expected behavior?

The configuration should be saved with the kit.

### What hardware did you reproduce it with?

OLED

### What firmware did you reproduce it with?

Release 1.1/Beethoven

### If possible provide the steps to reproduce the issue and upload additional media:

In a kit, 
-press [AUDITION] pad + [Midi] to convert the row in midi row
-then choosing midi channel and note with gold knobs.
-Save the kit.

- When reloading the kit the configuration is lost.

**Comment by seangoodvibes** [comment] 2024-09-15 20:14
Midi isn't saved with presets, it's saved with the song. This is a bigger issue.

**Comment by bukru** [comment] 2024-09-16 07:17
Thanks for answer,

Is it possible to copy/paste a clip and his midi configuration from a song to another ?

**Comment by m-m-adams** [comment] 2024-09-17 00:50
@seangoodvibes Midi drums are still saved in the kit and I think that's what's being described 

I can't reproduce this though. Midi rows in my kits are loading fine

**Comment by seangoodvibes** [comment] 2024-09-17 00:55
> @seangoodvibes Midi drums are still saved in the kit and I think that's what's being described
> 
> I can't reproduce this though. Midi rows in my kits are loading fine

ah yea that works fine for me too.

**Comment by bukru** [comment] 2024-09-17 08:18
Thanks to all of you as always for your support :+1:   

So i retry the stuff, and as you say me it work fine for you i searched what i did wrong and ... i think i found it !

When saving : 
- <save> + <kit>  (ok)
- select with <select> knob OR write a name with keyboard (ok)

- and then here is it :
     IF you write a new name then press "enter" with the keyboard layout, it saved the new kit
     **BUT IF you select a existing kit, then press "enter" with the keyboard layout, it will ask for "overwrite ?", then press "enter" again, and it will do nothing actually.** 

As a conclusion : i was thinking to save the kit, but actually not >__________<

Now i know it but i think i will do this error sometimes again.

**Comment by bukru** [comment] 2024-09-17 08:24
Do you think i should post an other issue for that or i just close the thread ?

**Comment by seangoodvibes** [comment] 2024-09-17 15:35
> Do you think i should post an other issue for that or i just close the thread ?

So if I'm understanding correctly, what you're saying is that when you press enter to overwrite an existing kit, it's not saving your midi changes into that overwritten kit. I can test that

**Comment by bukru** [comment] 2024-09-17 15:59
Actually i think it save nothing in that situation

**Comment by bukru** [comment] 2024-09-19 13:34
When saving :

    < save > + < kit > (ok)

    select with < select > knob OR write a name with keyboard (ok)

    and then here is it :
    IF you write a new name then press "enter" **with the keyboard layout** (the green "key" on the right), it saved the new kit

    **BUT IF** you select a existing kit, then press "enter" **with the keyboard layout  (the green "key" on the right)**, it will ask for "overwrite ?", then press "enter" again  **(the green "key" on the right)**, and it will do nothing actually, just close the popup


maybe i should made a video ?

**Comment by m-m-adams** [comment] 2024-10-01 20:12
Fixed by #2612

**Closed by m-m-adams** 2024-10-01 20:12 UTC
Labels: no-repro
